"""users_products_purchases

Revision ID: V001
Revises: 
Create Date: 2024-05-02 17:13:07.735699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'V001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.CheckConstraint('price >= 0'),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('type', 'name')
    )
    op.create_index('type', 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('steam_id', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='amount_positive_check'),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_table('purchases',
    sa.Column('purchase_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['steam_id'], ['users.steam_id'], ),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('steam_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.drop_table('users')
    op.drop_index('type', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
